id: P010440
initial_creation_type: ocr
created_at: 26/03/2020
last_modified_at: 2021-12-19 20:50:01.299615
source_metadata:
  id: bdr:W19617
  title: གསུང་འབུམ། ངག་དབང་ཕུན་ཚོགས
  author: ''
  volumes:
    db51b8762f2c4197a2a1a21ba161930e:
      image_group_id: I4976
      title: ''
      volume_number: 1
      total_pages: 567
      base_file: v001.txt
    54d402edb1dd4b90a6f74ead2ad7981a:
      image_group_id: I4977
      title: ''
      volume_number: 2
      total_pages: 542
      base_file: v002.txt
    1975b3d830f94e09a125dac8392fd661:
      image_group_id: I4978
      title: ''
      volume_number: 3
      total_pages: 644
      base_file: v003.txt
    1fb3862fd7ea4d3a8e23ee8f0f803537:
      image_group_id: I4979
      title: ''
      volume_number: 4
      total_pages: 568
      base_file: v004.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
